'use strict';

var tickers = [
  {sym: 'MMM', name: '3M Company', industry: 'Industrials'},
  {sym: 'ABT', name: 'Abbott Laboratories', industry: 'Health Care'},
  {sym: 'ABBV', name: 'AbbVie', industry: 'Health Care'},
  {sym: 'ACN', name: 'Accenture plc', industry: 'Information Technology'},
  {
    sym: 'ATVI',
    name: 'Activision Blizzard',
    industry: 'Information Technology'
  },
  {sym: 'AYI', name: 'Acuity Brands Inc', industry: 'Industrials'},
  {sym: 'ADBE', name: 'Adobe Systems Inc', industry: 'Information Technology'},
  {sym: 'AAP', name: 'Advance Auto Parts', industry: 'Consumer Discretionary'},
  {sym: 'AES', name: 'AES Corp', industry: 'Utilities'},
  {sym: 'AET', name: 'Aetna Inc', industry: 'Health Care'},
  {sym: 'AMG', name: 'Affiliated Managers Group Inc', industry: 'Financials'},
  {sym: 'AFL', name: 'AFLAC Inc', industry: 'Financials'},
  {sym: 'A', name: 'Agilent Technologies Inc', industry: 'Health Care'},
  {sym: 'APD', name: 'Air Products & Chemicals Inc', industry: 'Materials'},
  {
    sym: 'AKAM',
    name: 'Akamai Technologies Inc',
    industry: 'Information Technology'
  },
  {sym: 'ALK', name: 'Alaska Air Group Inc', industry: 'Industrials'},
  {sym: 'ALB', name: 'Albemarle Corp', industry: 'Materials'},
  {sym: 'ALXN', name: 'Alexion Pharmaceuticals', industry: 'Health Care'},
  {sym: 'ALLE', name: 'Allegion', industry: 'Industrials'},
  {sym: 'AGN', name: 'Allergan, Plc', industry: 'Health Care'},
  {
    sym: 'ADS',
    name: 'Alliance Data Systems',
    industry: 'Information Technology'
  },
  {sym: 'LNT', name: 'Alliant Energy Corp', industry: 'Utilities'},
  {sym: 'ALL', name: 'Allstate Corp', industry: 'Financials'},
  {
    sym: 'GOOGL',
    name: 'Alphabet Inc Class A',
    industry: 'Information Technology'
  },
  {
    sym: 'GOOG',
    name: 'Alphabet Inc Class C',
    industry: 'Information Technology'
  },
  {sym: 'MO', name: 'Altria Group Inc', industry: 'Consumer Staples'},
  {sym: 'AMZN', name: 'Amazon.com Inc', industry: 'Consumer Discretionary'},
  {sym: 'AEE', name: 'Ameren Corp', industry: 'Utilities'},
  {sym: 'AAL', name: 'American Airlines Group', industry: 'Industrials'},
  {sym: 'AEP', name: 'American Electric Power', industry: 'Utilities'},
  {sym: 'AXP', name: 'American Express Co', industry: 'Financials'},
  {
    sym: 'AIG',
    name: 'American International Group, Inc.',
    industry: 'Financials'
  },
  {sym: 'AMT', name: 'American Tower Corp A', industry: 'Real Estate'},
  {sym: 'AWK', name: 'American Water Works Company Inc', industry: 'Utilities'},
  {sym: 'AMP', name: 'Ameriprise Financial', industry: 'Financials'},
  {sym: 'ABC', name: 'AmerisourceBergen Corp', industry: 'Health Care'},
  {sym: 'AME', name: 'AMETEK Inc', industry: 'Industrials'},
  {sym: 'AMGN', name: 'Amgen Inc', industry: 'Health Care'},
  {sym: 'APH', name: 'Amphenol Corp', industry: 'Information Technology'},
  {sym: 'APC', name: 'Anadarko Petroleum Corp', industry: 'Energy'},
  {
    sym: 'ADI',
    name: 'Analog Devices, Inc.',
    industry: 'Information Technology'
  },
  {sym: 'ANTM', name: 'Anthem Inc.', industry: 'Health Care'},
  {sym: 'AON', name: 'Aon plc', industry: 'Financials'},
  {sym: 'APA', name: 'Apache Corporation', industry: 'Energy'},
  {sym: 'AIV', name: 'Apartment Investment & Mgmt', industry: 'Real Estate'},
  {sym: 'AAPL', name: 'Apple Inc.', industry: 'Information Technology'},
  {
    sym: 'AMAT',
    name: 'Applied Materials Inc',
    industry: 'Information Technology'
  },
  {sym: 'ADM', name: 'Archer-Daniels-Midland Co', industry: 'Consumer Staples'},
  {sym: 'ARNC', name: 'Arconic Inc', industry: 'Industrials'},
  {sym: 'AJG', name: 'Arthur J. Gallagher & Co.', industry: 'Financials'},
  {sym: 'AIZ', name: 'Assurant Inc', industry: 'Financials'},
  {sym: 'T', name: 'AT&T Inc', industry: 'Telecommunications Services'},
  {sym: 'ADSK', name: 'Autodesk Inc', industry: 'Information Technology'},
  {
    sym: 'ADP',
    name: 'Automatic Data Processing',
    industry: 'Information Technology'
  },
  {sym: 'AN', name: 'AutoNation Inc', industry: 'Consumer Discretionary'},
  {sym: 'AZO', name: 'AutoZone Inc', industry: 'Consumer Discretionary'},
  {sym: 'AVB', name: 'AvalonBay Communities, Inc.', industry: 'Real Estate'},
  {sym: 'AVY', name: 'Avery Dennison Corp', industry: 'Materials'},
  {sym: 'BHI', name: 'Baker Hughes Inc', industry: 'Energy'},
  {sym: 'BLL', name: 'Ball Corp', industry: 'Materials'},
  {sym: 'BAC', name: 'Bank of America Corp', industry: 'Financials'},
  {sym: 'BCR', name: 'Bard (C.R.) Inc.', industry: 'Health Care'},
  {sym: 'BAX', name: 'Baxter International Inc.', industry: 'Health Care'},
  {sym: 'BBT', name: 'BB&T Corporation', industry: 'Financials'},
  {sym: 'BDX', name: 'Becton Dickinson', industry: 'Health Care'},
  {sym: 'BBBY', name: 'Bed Bath & Beyond', industry: 'Consumer Discretionary'},
  {sym: 'BRK.B', name: 'Berkshire Hathaway', industry: 'Financials'},
  {sym: 'BBY', name: 'Best Buy Co. Inc.', industry: 'Consumer Discretionary'},
  {sym: 'BIIB', name: 'BIOGEN IDEC Inc.', industry: 'Health Care'},
  {sym: 'BLK', name: 'BlackRock', industry: 'Financials'},
  {sym: 'HRB', name: 'Block H&R', industry: 'Financials'},
  {sym: 'BA', name: 'Boeing Company', industry: 'Industrials'},
  {sym: 'BWA', name: 'BorgWarner', industry: 'Consumer Discretionary'},
  {sym: 'BXP', name: 'Boston Properties', industry: 'Real Estate'},
  {sym: 'BSX', name: 'Boston Scientific', industry: 'Health Care'},
  {sym: 'BMY', name: 'Bristol-Myers Squibb', industry: 'Health Care'},
  {sym: 'AVGO', name: 'Broadcom', industry: 'Information Technology'},
  {sym: 'BF.B', name: 'Brown-Forman Corp.', industry: 'Consumer Staples'},
  {sym: 'CHRW', name: 'C. H. Robinson Worldwide', industry: 'Industrials'},
  {sym: 'CA', name: 'CA, Inc.', industry: 'Information Technology'},
  {sym: 'COG', name: 'Cabot Oil & Gas', industry: 'Energy'},
  {sym: 'CPB', name: 'Campbell Soup', industry: 'Consumer Staples'},
  {sym: 'COF', name: 'Capital One Financial', industry: 'Financials'},
  {sym: 'CAH', name: 'Cardinal Health Inc.', industry: 'Health Care'},
  {sym: 'KMX', name: 'Carmax Inc', industry: 'Consumer Discretionary'},
  {sym: 'CCL', name: 'Carnival Corp.', industry: 'Consumer Discretionary'},
  {sym: 'CAT', name: 'Caterpillar Inc.', industry: 'Industrials'},
  {sym: 'CBOE', name: 'CBOE Holdings', industry: 'Financials'},
  {sym: 'CBG', name: 'CBRE Group', industry: 'Real Estate'},
  {sym: 'CBS', name: 'CBS Corp.', industry: 'Consumer Discretionary'},
  {sym: 'CELG', name: 'Celgene Corp.', industry: 'Health Care'},
  {sym: 'CNC', name: 'Centene Corporation', industry: 'Health Care'},
  {sym: 'CNP', name: 'CenterPoint Energy', industry: 'Utilities'},
  {
    sym: 'CTL',
    name: 'CenturyLink Inc',
    industry: 'Telecommunications Services'
  },
  {sym: 'CERN', name: 'Cerner', industry: 'Health Care'},
  {sym: 'CF', name: 'CF Industries Holdings Inc', industry: 'Materials'},
  {sym: 'SCHW', name: 'Charles Schwab Corporation', industry: 'Financials'},
  {
    sym: 'CHTR',
    name: 'Charter Communications',
    industry: 'Consumer Discretionary'
  },
  {sym: 'CHK', name: 'Chesapeake Energy', industry: 'Energy'},
  {sym: 'CVX', name: 'Chevron Corp.', industry: 'Energy'},
  {
    sym: 'CMG',
    name: 'Chipotle Mexican Grill',
    industry: 'Consumer Discretionary'
  },
  {sym: 'CB', name: 'Chubb Limited', industry: 'Financials'},
  {sym: 'CHD', name: 'Church & Dwight', industry: 'Consumer Staples'},
  {sym: 'CI', name: 'CIGNA Corp.', industry: 'Health Care'},
  {sym: 'XEC', name: 'Cimarex Energy', industry: 'Energy'},
  {sym: 'CINF', name: 'Cincinnati Financial', industry: 'Financials'},
  {sym: 'CTAS', name: 'Cintas Corporation', industry: 'Industrials'},
  {sym: 'CSCO', name: 'Cisco Systems', industry: 'Information Technology'},
  {sym: 'C', name: 'Citigroup Inc.', industry: 'Financials'},
  {sym: 'CFG', name: 'Citizens Financial Group', industry: 'Financials'},
  {sym: 'CTXS', name: 'Citrix Systems', industry: 'Information Technology'},
  {sym: 'CME', name: 'CME Group Inc.', industry: 'Financials'},
  {sym: 'CMS', name: 'CMS Energy', industry: 'Utilities'},
  {sym: 'COH', name: 'Coach Inc.', industry: 'Consumer Discretionary'},
  {sym: 'KO', name: 'Coca Cola Company', industry: 'Consumer Staples'},
  {
    sym: 'CTSH',
    name: 'Cognizant Technology Solutions',
    industry: 'Information Technology'
  },
  {sym: 'CL', name: 'Colgate-Palmolive', industry: 'Consumer Staples'},
  {sym: 'CMCSA', name: 'Comcast Corp.', industry: 'Consumer Discretionary'},
  {sym: 'CMA', name: 'Comerica Inc.', industry: 'Financials'},
  {sym: 'CAG', name: 'ConAgra Foods Inc.', industry: 'Consumer Staples'},
  {sym: 'CXO', name: 'Concho Resources', industry: 'Energy'},
  {sym: 'COP', name: 'ConocoPhillips', industry: 'Energy'},
  {sym: 'ED', name: 'Consolidated Edison', industry: 'Utilities'},
  {sym: 'STZ', name: 'Constellation Brands', industry: 'Consumer Staples'},
  {sym: 'GLW', name: 'Corning Inc.', industry: 'Information Technology'},
  {sym: 'COST', name: 'Costco Co.', industry: 'Consumer Staples'},
  {sym: 'COTY', name: 'Coty, Inc', industry: 'Consumer Staples'},
  {
    sym: 'CCI',
    name: 'Crown Castle International Corp.',
    industry: 'Real Estate'
  },
  {sym: 'CSRA', name: 'CSRA Inc.', industry: 'Information Technology'},
  {sym: 'CSX', name: 'CSX Corp.', industry: 'Industrials'},
  {sym: 'CMI', name: 'Cummins Inc.', industry: 'Industrials'},
  {sym: 'CVS', name: 'CVS Health', industry: 'Consumer Staples'},
  {sym: 'DHI', name: 'D. R. Horton', industry: 'Consumer Discretionary'},
  {sym: 'DHR', name: 'Danaher Corp.', industry: 'Health Care'},
  {sym: 'DRI', name: 'Darden Restaurants', industry: 'Consumer Discretionary'},
  {sym: 'DVA', name: 'DaVita Inc.', industry: 'Health Care'},
  {sym: 'DE', name: 'Deere & Co.', industry: 'Industrials'},
  {sym: 'DLPH', name: 'Delphi Automotive', industry: 'Consumer Discretionary'},
  {sym: 'DAL', name: 'Delta Air Lines', industry: 'Industrials'},
  {sym: 'XRAY', name: 'Dentsply Sirona', industry: 'Health Care'},
  {sym: 'DVN', name: 'Devon Energy Corp.', industry: 'Energy'},
  {sym: 'DLR', name: 'Digital Realty Trust', industry: 'Real Estate'},
  {sym: 'DFS', name: 'Discover Financial Services', industry: 'Financials'},
  {
    sym: 'DISCA',
    name: 'Discovery Communications-A',
    industry: 'Consumer Discretionary'
  },
  {
    sym: 'DISCK',
    name: 'Discovery Communications-C',
    industry: 'Consumer Discretionary'
  },
  {sym: 'DG', name: 'Dollar General', industry: 'Consumer Discretionary'},
  {sym: 'DLTR', name: 'Dollar Tree', industry: 'Consumer Discretionary'},
  {sym: 'D', name: 'Dominion Resources', industry: 'Utilities'},
  {sym: 'DOV', name: 'Dover Corp.', industry: 'Industrials'},
  {sym: 'DOW', name: 'Dow Chemical', industry: 'Materials'},
  {sym: 'DPS', name: 'Dr Pepper Snapple Group', industry: 'Consumer Staples'},
  {sym: 'DTE', name: 'DTE Energy Co.', industry: 'Utilities'},
  {sym: 'DD', name: 'Du Pont (E.I.)', industry: 'Materials'},
  {sym: 'DUK', name: 'Duke Energy', industry: 'Utilities'},
  {sym: 'DNB', name: 'Dun & Bradstreet', industry: 'Industrials'},
  {sym: 'ETFC', name: 'E*Trade', industry: 'Financials'},
  {sym: 'EMN', name: 'Eastman Chemical', industry: 'Materials'},
  {sym: 'ETN', name: 'Eaton Corporation', industry: 'Industrials'},
  {sym: 'EBAY', name: 'eBay Inc.', industry: 'Information Technology'},
  {sym: 'ECL', name: 'Ecolab Inc.', industry: 'Materials'},
  {sym: 'EIX', name: 'Edison Int\'l', industry: 'Utilities'},
  {sym: 'EW', name: 'Edwards Lifesciences', industry: 'Health Care'},
  {sym: 'EA', name: 'Electronic Arts', industry: 'Information Technology'},
  {sym: 'EMR', name: 'Emerson Electric Company', industry: 'Industrials'},
  {sym: 'ETR', name: 'Entergy Corp.', industry: 'Utilities'},
  {sym: 'EVHC', name: 'Envision Healthcare', industry: 'Health Care'},
  {sym: 'EOG', name: 'EOG Resources', industry: 'Energy'},
  {sym: 'EQT', name: 'EQT Corporation', industry: 'Energy'},
  {sym: 'EFX', name: 'Equifax Inc.', industry: 'Industrials'},
  {sym: 'EQIX', name: 'Equinix', industry: 'Real Estate'},
  {sym: 'EQR', name: 'Equity Residential', industry: 'Real Estate'},
  {sym: 'ESS', name: 'Essex Property Trust, Inc.', industry: 'Real Estate'},
  {sym: 'EL', name: 'Estee Lauder Cos.', industry: 'Consumer Staples'},
  {sym: 'ES', name: 'Eversource Energy', industry: 'Utilities'},
  {sym: 'EXC', name: 'Exelon Corp.', industry: 'Utilities'},
  {sym: 'EXPE', name: 'Expedia Inc.', industry: 'Consumer Discretionary'},
  {sym: 'EXPD', name: 'Expeditors Int\'l', industry: 'Industrials'},
  {sym: 'ESRX', name: 'Express Scripts', industry: 'Health Care'},
  {sym: 'EXR', name: 'Extra Space Storage', industry: 'Real Estate'},
  {sym: 'XOM', name: 'Exxon Mobil Corp.', industry: 'Energy'},
  {sym: 'FFIV', name: 'F5 Networks', industry: 'Information Technology'},
  {sym: 'FB', name: 'Facebook, Inc.', industry: 'Information Technology'},
  {sym: 'FAST', name: 'Fastenal Co', industry: 'Industrials'},
  {
    sym: 'FRT',
    name: 'Federal Realty Investment Trust',
    industry: 'Real Estate'
  },
  {sym: 'FDX', name: 'FedEx Corporation', industry: 'Industrials'},
  {
    sym: 'FIS',
    name: 'Fidelity National Information Services',
    industry: 'Information Technology'
  },
  {sym: 'FITB', name: 'Fifth Third Bancorp', industry: 'Financials'},
  {sym: 'FSLR', name: 'First Solar Inc', industry: 'Information Technology'},
  {sym: 'FE', name: 'FirstEnergy Corp', industry: 'Utilities'},
  {sym: 'FISV', name: 'Fiserv Inc', industry: 'Information Technology'},
  {sym: 'FLIR', name: 'FLIR Systems', industry: 'Information Technology'},
  {sym: 'FLS', name: 'Flowserve Corporation', industry: 'Industrials'},
  {sym: 'FLR', name: 'Fluor Corp.', industry: 'Industrials'},
  {sym: 'FMC', name: 'FMC Corporation', industry: 'Materials'},
  {sym: 'FTI', name: 'FMC Technologies Inc.', industry: 'Energy'},
  {sym: 'FL', name: 'Foot Locker Inc', industry: 'Consumer Discretionary'},
  {sym: 'F', name: 'Ford Motor', industry: 'Consumer Discretionary'},
  {sym: 'FTV', name: 'Fortive Corp', industry: 'Industrials'},
  {
    sym: 'FBHS',
    name: 'Fortune Brands Home & Security',
    industry: 'Industrials'
  },
  {sym: 'BEN', name: 'Franklin Resources', industry: 'Financials'},
  {sym: 'FCX', name: 'Freeport-McMoRan Inc.', industry: 'Materials'},
  {
    sym: 'FTR',
    name: 'Frontier Communications',
    industry: 'Telecommunications Services'
  },
  {sym: 'GPS', name: 'Gap (The)', industry: 'Consumer Discretionary'},
  {sym: 'GRMN', name: 'Garmin Ltd.', industry: 'Consumer Discretionary'},
  {sym: 'GD', name: 'General Dynamics', industry: 'Industrials'},
  {sym: 'GE', name: 'General Electric', industry: 'Industrials'},
  {sym: 'GGP', name: 'General Growth Properties Inc.', industry: 'Real Estate'},
  {sym: 'GIS', name: 'General Mills', industry: 'Consumer Staples'},
  {sym: 'GM', name: 'General Motors', industry: 'Consumer Discretionary'},
  {sym: 'GPC', name: 'Genuine Parts', industry: 'Consumer Discretionary'},
  {sym: 'GILD', name: 'Gilead Sciences', industry: 'Health Care'},
  {sym: 'GPN', name: 'Global Payments Inc', industry: 'Information Technology'},
  {sym: 'GS', name: 'Goldman Sachs Group', industry: 'Financials'},
  {
    sym: 'GT',
    name: 'Goodyear Tire & Rubber',
    industry: 'Consumer Discretionary'
  },
  {sym: 'GWW', name: 'Grainger (W.W.) Inc.', industry: 'Industrials'},
  {sym: 'HAL', name: 'Halliburton Co.', industry: 'Energy'},
  {sym: 'HBI', name: 'Hanesbrands Inc', industry: 'Consumer Discretionary'},
  {sym: 'HOG', name: 'Harley-Davidson', industry: 'Consumer Discretionary'},
  {
    sym: 'HAR',
    name: 'Harman Int\'l Industries',
    industry: 'Consumer Discretionary'
  },
  {sym: 'HRS', name: 'Harris Corporation', industry: 'Information Technology'},
  {sym: 'HIG', name: 'Hartford Financial Svc.Gp.', industry: 'Financials'},
  {sym: 'HAS', name: 'Hasbro Inc.', industry: 'Consumer Discretionary'},
  {sym: 'HCA', name: 'HCA Holdings', industry: 'Health Care'},
  {sym: 'HCP', name: 'HCP Inc.', industry: 'Real Estate'},
  {sym: 'HP', name: 'Helmerich & Payne', industry: 'Energy'},
  {sym: 'HSIC', name: 'Henry Schein', industry: 'Health Care'},
  {sym: 'HES', name: 'Hess Corporation', industry: 'Energy'},
  {
    sym: 'HPE',
    name: 'Hewlett Packard Enterprise',
    industry: 'Information Technology'
  },
  {sym: 'HOLX', name: 'Hologic', industry: 'Health Care'},
  {sym: 'HD', name: 'Home Depot', industry: 'Consumer Discretionary'},
  {
    sym: 'HON', name: 'Honeywell Int\'l Inc.', industry: 'Industrials'
  },
  {sym: 'HRL', name: 'Hormel Foods Corp.', industry: 'Consumer Staples'},
  {sym: 'HST', name: 'Host Hotels & Resorts', industry: 'Real Estate'},
  {sym: 'HPQ', name: 'HP Inc.', industry: 'Information Technology'},
  {sym: 'HUM', name: 'Humana Inc.', industry: 'Health Care'},
  {sym: 'HBAN', name: 'Huntington Bancshares', industry: 'Financials'},
  {sym: 'IDXX', name: 'IDEXX Laboratories', industry: 'Health Care'},
  {sym: 'ITW', name: 'Illinois Tool Works', industry: 'Industrials'},
  {sym: 'ILMN', name: 'Illumina Inc', industry: 'Health Care'},
  {sym: 'INCY', name: 'Incyte', industry: 'Health Care'},
  {sym: 'IR', name: 'Ingersoll-Rand PLC', industry: 'Industrials'},
  {sym: 'INTC', name: 'Intel Corp.', industry: 'Information Technology'},
  {sym: 'ICE', name: 'Intercontinental Exchange', industry: 'Financials'},
  {
    sym: 'IBM',
    name: 'International Business Machines',
    industry: 'Information Technology'
  },
  {sym: 'IP', name: 'International Paper', industry: 'Materials'},
  {sym: 'IPG', name: 'Interpublic Group', industry: 'Consumer Discretionary'},
  {sym: 'IFF', name: 'Intl Flavors & Fragrances', industry: 'Materials'},
  {sym: 'INTU', name: 'Intuit Inc.', industry: 'Information Technology'},
  {sym: 'ISRG', name: 'Intuitive Surgical Inc.', industry: 'Health Care'},
  {sym: 'IVZ', name: 'Invesco Ltd.', industry: 'Financials'},
  {sym: 'IRM', name: 'Iron Mountain Incorporated', industry: 'Real Estate'},
  {sym: 'JBHT', name: 'J. B. Hunt Transport Services', industry: 'Industrials'},
  {sym: 'JEC', name: 'Jacobs Engineering Group', industry: 'Industrials'},
  {sym: 'SJM', name: 'JM Smucker', industry: 'Consumer Staples'},
  {sym: 'JNJ', name: 'Johnson & Johnson', industry: 'Health Care'},
  {sym: 'JCI', name: 'Johnson Controls International', industry: 'Industrials'},
  {sym: 'JPM', name: 'JPMorgan Chase & Co.', industry: 'Financials'},
  {sym: 'JNPR', name: 'Juniper Networks', industry: 'Information Technology'},
  {sym: 'KSU', name: 'Kansas City Southern', industry: 'Industrials'},
  {sym: 'K', name: 'Kellogg Co.', industry: 'Consumer Staples'},
  {sym: 'KEY', name: 'KeyCorp', industry: 'Financials'},
  {sym: 'KMB', name: 'Kimberly-Clark', industry: 'Consumer Staples'},
  {sym: 'KIM', name: 'Kimco Realty', industry: 'Real Estate'},
  {sym: 'KMI', name: 'Kinder Morgan', industry: 'Energy'},
  {sym: 'KLAC', name: 'KLA-Tencor Corp.', industry: 'Information Technology'},
  {sym: 'KSS', name: 'Kohl\'s Corp.', industry: 'Consumer Discretionary'},
  {sym: 'KHC', name: 'Kraft Heinz Co', industry: 'Consumer Staples'},
  {sym: 'KR', name: 'Kroger Co.', industry: 'Consumer Staples'},
  {sym: 'LB', name: 'L Brands Inc.', industry: 'Consumer Discretionary'},
  {sym: 'LLL', name: 'L-3 Communications Holdings', industry: 'Industrials'},
  {
    sym: 'LH',
    name: 'Laboratory Corp. of America Holding',
    industry: 'Health Care'
  },
  {sym: 'LRCX', name: 'Lam Research', industry: 'Information Technology'},
  {sym: 'LEG', name: 'Leggett & Platt', industry: 'Consumer Discretionary'},
  {sym: 'LEN', name: 'Lennar Corp.', industry: 'Consumer Discretionary'},
  {sym: 'LUK', name: 'Leucadia National Corp.', industry: 'Financials'},
  {
    sym: 'LVLT',
    name: 'Level 3 Communications',
    industry: 'Telecommunications Services'
  },
  {sym: 'LLY', name: 'Lilly (Eli) & Co.', industry: 'Health Care'},
  {sym: 'LNC', name: 'Lincoln National', industry: 'Financials'},
  {
    sym: 'LLTC',
    name: 'Linear Technology Corp.',
    industry: 'Information Technology'
  },
  {sym: 'LKQ', name: 'LKQ Corporation', industry: 'Consumer Discretionary'},
  {sym: 'LMT', name: 'Lockheed Martin Corp.', industry: 'Industrials'},
  {sym: 'L', name: 'Loews Corp.', industry: 'Financials'},
  {sym: 'LOW', name: 'Lowe\'s Cos.', industry: 'Consumer Discretionary'},
  {sym: 'LYB', name: 'LyondellBasell', industry: 'Materials'},
  {sym: 'MTB', name: 'M&T Bank Corp.', industry: 'Financials'},
  {sym: 'MAC', name: 'Macerich', industry: 'Real Estate'},
  {sym: 'M', name: 'Macy\'s Inc.', industry: 'Consumer Discretionary'},
  {sym: 'MNK', name: 'Mallinckrodt Plc', industry: 'Health Care'},
  {sym: 'MRO', name: 'Marathon Oil Corp.', industry: 'Energy'},
  {sym: 'MPC', name: 'Marathon Petroleum', industry: 'Energy'},
  {sym: 'MAR', name: 'Marriott Int\'l.', industry: 'Consumer Discretionary'},
  {sym: 'MMC', name: 'Marsh & McLennan', industry: 'Financials'},
  {sym: 'MLM', name: 'Martin Marietta Materials', industry: 'Materials'},
  {sym: 'MAS', name: 'Masco Corp.', industry: 'Industrials'},
  {sym: 'MA', name: 'Mastercard Inc.', industry: 'Information Technology'},
  {sym: 'MAT', name: 'Mattel Inc.', industry: 'Consumer Discretionary'},
  {sym: 'MKC', name: 'McCormick & Co.', industry: 'Consumer Staples'},
  {sym: 'MCD', name: 'McDonald\'s Corp.', industry: 'Consumer Discretionary'},
  {sym: 'MCK', name: 'McKesson Corp.', industry: 'Health Care'},
  {sym: 'MJN', name: 'Mead Johnson', industry: 'Consumer Staples'},
  {sym: 'MDT', name: 'Medtronic plc', industry: 'Health Care'},
  {sym: 'MRK', name: 'Merck & Co.', industry: 'Health Care'},
  {sym: 'MET', name: 'MetLife Inc.', industry: 'Financials'},
  {sym: 'MTD', name: 'Mettler Toledo', industry: 'Health Care'},
  {
    sym: 'KORS',
    name: 'Michael Kors Holdings',
    industry: 'Consumer Discretionary'
  },
  {
    sym: 'MCHP',
    name: 'Microchip Technology',
    industry: 'Information Technology'
  },
  {sym: 'MU', name: 'Micron Technology', industry: 'Information Technology'},
  {sym: 'MSFT', name: 'Microsoft Corp.', industry: 'Information Technology'},
  {sym: 'MAA', name: 'Mid-America Apartments', industry: 'Real Estate'},
  {sym: 'MHK', name: 'Mohawk Industries', industry: 'Consumer Discretionary'},
  {
    sym: 'TAP',
    name: 'Molson Coors Brewing Company',
    industry: 'Consumer Staples'
  },
  {sym: 'MDLZ', name: 'Mondelez International', industry: 'Consumer Staples'},
  {sym: 'MON', name: 'Monsanto Co.', industry: 'Materials'},
  {sym: 'MNST', name: 'Monster Beverage', industry: 'Consumer Staples'},
  {
    sym: 'MCO', name: 'Moody\'s Corp', industry: 'Financials'
  },
  {sym: 'MS', name: 'Morgan Stanley', industry: 'Financials'},
  {
    sym: 'MSI',
    name: 'Motorola Solutions Inc.',
    industry: 'Information Technology'
  },
  {sym: 'MUR', name: 'Murphy Oil', industry: 'Energy'},
  {sym: 'MYL', name: 'Mylan N.V.', industry: 'Health Care'},
  {sym: 'NDAQ', name: 'NASDAQ OMX Group', industry: 'Financials'},
  {sym: 'NOV', name: 'National Oilwell Varco Inc.', industry: 'Energy'},
  {sym: 'NAVI', name: 'Navient', industry: 'Financials'},
  {sym: 'NTAP', name: 'NetApp', industry: 'Information Technology'},
  {sym: 'NFLX', name: 'Netflix Inc.', industry: 'Information Technology'},
  {sym: 'NWL', name: 'Newell Brands', industry: 'Consumer Discretionary'},
  {sym: 'NFX', name: 'Newfield Exploration Co', industry: 'Energy'},
  {sym: 'NEM', name: 'Newmont Mining Corp. (Hldg. Co.)', industry: 'Materials'},
  {sym: 'NWSA', name: 'News Corp. Class A', industry: 'Consumer Discretionary'},
  {sym: 'NWS', name: 'News Corp. Class B', industry: 'Consumer Discretionary'},
  {sym: 'NEE', name: 'NextEra Energy', industry: 'Utilities'},
  {sym: 'NLSN', name: 'Nielsen Holdings', industry: 'Industrials'},
  {sym: 'NKE', name: 'Nike', industry: 'Consumer Discretionary'},
  {sym: 'NI', name: 'NiSource Inc.', industry: 'Utilities'},
  {sym: 'NBL', name: 'Noble Energy Inc', industry: 'Energy'},
  {sym: 'JWN', name: 'Nordstrom', industry: 'Consumer Discretionary'},
  {sym: 'NSC', name: 'Norfolk Southern Corp.', industry: 'Industrials'},
  {sym: 'NTRS', name: 'Northern Trust Corp.', industry: 'Financials'},
  {sym: 'NOC', name: 'Northrop Grumman Corp.', industry: 'Industrials'},
  {sym: 'NRG', name: 'NRG Energy', industry: 'Utilities'},
  {sym: 'NUE', name: 'Nucor Corp.', industry: 'Materials'},
  {sym: 'NVDA', name: 'Nvidia Corporation', industry: 'Information Technology'},
  {
    sym: 'ORLY',
    name: 'O\'Reilly Automotive',
    industry: 'Consumer Discretionary'
  },
  {sym: 'OXY', name: 'Occidental Petroleum', industry: 'Energy'},
  {sym: 'OMC', name: 'Omnicom Group', industry: 'Consumer Discretionary'},
  {sym: 'OKE', name: 'ONEOK', industry: 'Energy'},
  {sym: 'ORCL', name: 'Oracle Corp.', industry: 'Information Technology'},
  {sym: 'PCAR', name: 'PACCAR Inc.', industry: 'Industrials'},
  {sym: 'PH', name: 'Parker-Hannifin', industry: 'Industrials'},
  {sym: 'PDCO', name: 'Patterson Companies', industry: 'Health Care'},
  {sym: 'PAYX', name: 'Paychex Inc.', industry: 'Information Technology'},
  {sym: 'PYPL', name: 'PayPal', industry: 'Information Technology'},
  {sym: 'PNR', name: 'Pentair Ltd.', industry: 'Industrials'},
  {sym: 'PBCT', name: 'People\'s United Financial', industry: 'Financials'},
  {sym: 'PEP', name: 'PepsiCo Inc.', industry: 'Consumer Staples'},
  {sym: 'PKI', name: 'PerkinElmer', industry: 'Health Care'},
  {sym: 'PRGO', name: 'Perrigo', industry: 'Health Care'},
  {sym: 'PFE', name: 'Pfizer Inc.', industry: 'Health Care'},
  {sym: 'PCG', name: 'PG&E Corp.', industry: 'Utilities'},
  {
    sym: 'PM',
    name: 'Philip Morris International',
    industry: 'Consumer Staples'
  },
  {sym: 'PSX', name: 'Phillips 66', industry: 'Energy'},
  {sym: 'PNW', name: 'Pinnacle West Capital', industry: 'Utilities'},
  {sym: 'PXD', name: 'Pioneer Natural Resources', industry: 'Energy'},
  {sym: 'PNC', name: 'PNC Financial Services', industry: 'Financials'},
  {
    sym: 'RL',
    name: 'Polo Ralph Lauren Corp.',
    industry: 'Consumer Discretionary'
  },
  {sym: 'PPG', name: 'PPG Industries', industry: 'Materials'},
  {sym: 'PPL', name: 'PPL Corp.', industry: 'Utilities'},
  {sym: 'PX', name: 'Praxair Inc.', industry: 'Materials'},
  {sym: 'PCLN', name: 'Priceline.com Inc', industry: 'Consumer Discretionary'},
  {sym: 'PFG', name: 'Principal Financial Group', industry: 'Financials'},
  {sym: 'PG', name: 'Procter & Gamble', industry: 'Consumer Staples'},
  {sym: 'PGR', name: 'Progressive Corp.', industry: 'Financials'},
  {sym: 'PLD', name: 'Prologis', industry: 'Real Estate'},
  {sym: 'PRU', name: 'Prudential Financial', industry: 'Financials'},
  {sym: 'PEG', name: 'Public Serv. Enterprise Inc.', industry: 'Utilities'},
  {sym: 'PSA', name: 'Public Storage', industry: 'Real Estate'},
  {sym: 'PHM', name: 'Pulte Homes Inc.', industry: 'Consumer Discretionary'},
  {sym: 'PVH', name: 'PVH Corp.', industry: 'Consumer Discretionary'},
  {sym: 'QRVO', name: 'Qorvo', industry: 'Information Technology'},
  {sym: 'QCOM', name: 'QUALCOMM Inc.', industry: 'Information Technology'},
  {sym: 'PWR', name: 'Quanta Services Inc.', industry: 'Industrials'},
  {sym: 'DGX', name: 'Quest Diagnostics', industry: 'Health Care'},
  {sym: 'RRC', name: 'Range Resources Corp.', industry: 'Energy'},
  {sym: 'RTN', name: 'Raytheon Co.', industry: 'Industrials'},
  {sym: 'O', name: 'Realty Income Corporation', industry: 'Real Estate'},
  {sym: 'RHT', name: 'Red Hat Inc.', industry: 'Information Technology'},
  {sym: 'REG', name: 'Regency Centers Corporation', industry: 'Real Estate'},
  {sym: 'REGN', name: 'Regeneron', industry: 'Health Care'},
  {sym: 'RF', name: 'Regions Financial Corp.', industry: 'Financials'},
  {sym: 'RSG', name: 'Republic Services Inc', industry: 'Industrials'},
  {sym: 'RAI', name: 'Reynolds American Inc.', industry: 'Consumer Staples'},
  {sym: 'RHI', name: 'Robert Half International', industry: 'Industrials'},
  {sym: 'ROK', name: 'Rockwell Automation Inc.', industry: 'Industrials'},
  {sym: 'COL', name: 'Rockwell Collins', industry: 'Industrials'},
  {sym: 'ROP', name: 'Roper Industries', industry: 'Industrials'},
  {sym: 'ROST', name: 'Ross Stores', industry: 'Consumer Discretionary'},
  {
    sym: 'RCL',
    name: 'Royal Caribbean Cruises Ltd',
    industry: 'Consumer Discretionary'
  },
  {sym: 'R', name: 'Ryder System', industry: 'Industrials'},
  {sym: 'SPGI', name: 'S&P Global, Inc.', industry: 'Financials'},
  {sym: 'CRM', name: 'Salesforce.com', industry: 'Information Technology'},
  {sym: 'SCG', name: 'SCANA Corp', industry: 'Utilities'},
  {sym: 'SLB', name: 'Schlumberger Ltd.', industry: 'Energy'},
  {
    sym: 'SNI',
    name: 'Scripps Networks Interactive Inc.',
    industry: 'Consumer Discretionary'
  },
  {sym: 'STX', name: 'Seagate Technology', industry: 'Information Technology'},
  {sym: 'SEE', name: 'Sealed Air', industry: 'Materials'},
  {sym: 'SRE', name: 'Sempra Energy', industry: 'Utilities'},
  {sym: 'SHW', name: 'Sherwin-Williams', industry: 'Materials'},
  {sym: 'SIG', name: 'Signet Jewelers', industry: 'Consumer Discretionary'},
  {sym: 'SPG', name: 'Simon Property Group Inc', industry: 'Real Estate'},
  {sym: 'SWKS', name: 'Skyworks Solutions', industry: 'Information Technology'},
  {sym: 'SLG', name: 'SL Green Realty', industry: 'Real Estate'},
  {sym: 'SNA', name: 'Snap-On Inc.', industry: 'Consumer Discretionary'},
  {sym: 'SO', name: 'Southern Co.', industry: 'Utilities'},
  {sym: 'LUV', name: 'Southwest Airlines', industry: 'Industrials'},
  {sym: 'SWN', name: 'Southwestern Energy', industry: 'Energy'},
  {
    sym: 'SWK',
    name: 'Stanley Black & Decker',
    industry: 'Consumer Discretionary'
  },
  {sym: 'SPLS', name: 'Staples Inc.', industry: 'Consumer Discretionary'},
  {sym: 'SBUX', name: 'Starbucks Corp.', industry: 'Consumer Discretionary'},
  {sym: 'STT', name: 'State Street Corp.', industry: 'Financials'},
  {sym: 'SRCL', name: 'Stericycle Inc', industry: 'Industrials'},
  {sym: 'SYK', name: 'Stryker Corp.', industry: 'Health Care'},
  {sym: 'STI', name: 'SunTrust Banks', industry: 'Financials'},
  {sym: 'SYMC', name: 'Symantec Corp.', industry: 'Information Technology'},
  {sym: 'SYF', name: 'Synchrony Financial', industry: 'Financials'},
  {sym: 'SYY', name: 'Sysco Corp.', industry: 'Consumer Staples'},
  {sym: 'TROW', name: 'T. Rowe Price Group', industry: 'Financials'},
  {sym: 'TGT', name: 'Target Corp.', industry: 'Consumer Discretionary'},
  {
    sym: 'TEL',
    name: 'TE Connectivity Ltd.',
    industry: 'Information Technology'
  },
  {sym: 'TGNA', name: 'Tegna, Inc.', industry: 'Consumer Discretionary'},
  {sym: 'TDC', name: 'Teradata Corp.', industry: 'Information Technology'},
  {sym: 'TSO', name: 'Tesoro Petroleum Co.', industry: 'Energy'},
  {sym: 'TXN', name: 'Texas Instruments', industry: 'Information Technology'},
  {sym: 'TXT', name: 'Textron Inc.', industry: 'Industrials'},
  {
    sym: 'BK',
    name: 'The Bank of New York Mellon Corp.',
    industry: 'Financials'
  },
  {sym: 'CLX', name: 'The Clorox Company', industry: 'Consumer Staples'},
  {sym: 'COO', name: 'The Cooper Companies', industry: 'Health Care'},
  {sym: 'HSY', name: 'The Hershey Company', industry: 'Consumer Staples'},
  {sym: 'MOS', name: 'The Mosaic Company', industry: 'Materials'},
  {sym: 'TRV', name: 'The Travelers Companies Inc.', industry: 'Financials'},
  {
    sym: 'DIS',
    name: 'The Walt Disney Company',
    industry: 'Consumer Discretionary'
  },
  {sym: 'TMO', name: 'Thermo Fisher Scientific', industry: 'Health Care'},
  {sym: 'TIF', name: 'Tiffany & Co.', industry: 'Consumer Discretionary'},
  {sym: 'TWX', name: 'Time Warner Inc.', industry: 'Consumer Discretionary'},
  {sym: 'TJX', name: 'TJX Companies Inc.', industry: 'Consumer Discretionary'},
  {sym: 'TMK', name: 'Torchmark Corp.', industry: 'Financials'},
  {
    sym: 'TSS',
    name: 'Total System Services',
    industry: 'Information Technology'
  },
  {
    sym: 'TSCO',
    name: 'Tractor Supply Company',
    industry: 'Consumer Discretionary'
  },
  {sym: 'TDG', name: 'TransDigm Group', industry: 'Industrials'},
  {sym: 'RIG', name: 'Transocean', industry: 'Energy'},
  {sym: 'TRIP', name: 'TripAdvisor', industry: 'Consumer Discretionary'},
  {
    sym: 'FOXA',
    name: 'Twenty-First Century Fox Class A',
    industry: 'Consumer Discretionary'
  },
  {
    sym: 'FOX',
    name: 'Twenty-First Century Fox Class B',
    industry: 'Consumer Discretionary'
  },
  {sym: 'TSN', name: 'Tyson Foods', industry: 'Consumer Staples'},
  {sym: 'USB', name: 'U.S. Bancorp', industry: 'Financials'},
  {sym: 'UDR', name: 'UDR Inc', industry: 'Real Estate'},
  {
    sym: 'ULTA',
    name: 'Ulta Salon Cosmetics & Fragrance Inc',
    industry: 'Consumer Discretionary'
  },
  {sym: 'UA', name: 'Under Armour', industry: 'Consumer Discretionary'},
  {sym: 'UAA', name: 'Under Armour', industry: 'Consumer Discretionary'},
  {sym: 'UNP', name: 'Union Pacific', industry: 'Industrials'},
  {sym: 'UAL', name: 'United Continental Holdings', industry: 'Industrials'},
  {sym: 'UNH', name: 'United Health Group Inc.', industry: 'Health Care'},
  {sym: 'UPS', name: 'United Parcel Service', industry: 'Industrials'},
  {sym: 'URI', name: 'United Rentals, Inc.', industry: 'Industrials'},
  {sym: 'UTX', name: 'United Technologies', industry: 'Industrials'},
  {
    sym: 'UHS',
    name: 'Universal Health Services, Inc.',
    industry: 'Industrials'
  },
  {sym: 'UNM', name: 'Unum Group', industry: 'Financials'},
  {sym: 'URBN', name: 'Urban Outfitters', industry: 'Consumer Discretionary'},
  {sym: 'VFC', name: 'V.F. Corp.', industry: 'Consumer Discretionary'},
  {sym: 'VLO', name: 'Valero Energy', industry: 'Energy'},
  {sym: 'VAR', name: 'Varian Medical Systems', industry: 'Health Care'},
  {sym: 'VTR', name: 'Ventas Inc', industry: 'Real Estate'},
  {sym: 'VRSN', name: 'Verisign Inc.', industry: 'Information Technology'},
  {sym: 'VRSK', name: 'Verisk Analytics', industry: 'Industrials'},
  {
    sym: 'VZ',
    name: 'Verizon Communications',
    industry: 'Telecommunications Services'
  },
  {sym: 'VRTX', name: 'Vertex Pharmaceuticals Inc', industry: 'Health Care'},
  {sym: 'VIAB', name: 'Viacom Inc.', industry: 'Consumer Discretionary'},
  {sym: 'V', name: 'Visa Inc.', industry: 'Information Technology'},
  {sym: 'VNO', name: 'Vornado Realty Trust', industry: 'Real Estate'},
  {sym: 'VMC', name: 'Vulcan Materials', industry: 'Materials'},
  {sym: 'WMT', name: 'Wal-Mart Stores', industry: 'Consumer Staples'},
  {sym: 'WBA', name: 'Walgreens Boots Alliance', industry: 'Consumer Staples'},
  {sym: 'WM', name: 'Waste Management Inc.', industry: 'Industrials'},
  {sym: 'WAT', name: 'Waters Corporation', industry: 'Health Care'},
  {sym: 'WEC', name: 'Wec Energy Group Inc', industry: 'Utilities'},
  {sym: 'WFC', name: 'Wells Fargo', industry: 'Financials'},
  {sym: 'HCN', name: 'Welltower Inc.', industry: 'Real Estate'},
  {sym: 'WDC', name: 'Western Digital', industry: 'Information Technology'},
  {sym: 'WU', name: 'Western Union Co', industry: 'Information Technology'},
  {sym: 'WRK', name: 'WestRock Company', industry: 'Materials'},
  {sym: 'WY', name: 'Weyerhaeuser Corp.', industry: 'Real Estate'},
  {sym: 'WHR', name: 'Whirlpool Corp.', industry: 'Consumer Discretionary'},
  {sym: 'WFM', name: 'Whole Foods Market', industry: 'Consumer Staples'},
  {sym: 'WMB', name: 'Williams Cos.', industry: 'Energy'},
  {sym: 'WLTW', name: 'Willis Towers Watson', industry: 'Financials'},
  {sym: 'WYN', name: 'Wyndham Worldwide', industry: 'Consumer Discretionary'},
  {sym: 'WYNN', name: 'Wynn Resorts Ltd', industry: 'Consumer Discretionary'},
  {sym: 'XEL', name: 'Xcel Energy Inc', industry: 'Utilities'},
  {sym: 'XRX', name: 'Xerox Corp.', industry: 'Information Technology'},
  {sym: 'XLNX', name: 'Xilinx Inc', industry: 'Information Technology'},
  {sym: 'XL', name: 'XL Capital', industry: 'Financials'},
  {sym: 'XYL', name: 'Xylem Inc.', industry: 'Industrials'},
  {sym: 'YHOO', name: 'Yahoo Inc.', industry: 'Information Technology'},
  {sym: 'YUM', name: 'Yum! Brands Inc', industry: 'Consumer Discretionary'},
  {sym: 'ZBH', name: 'Zimmer Biomet Holdings', industry: 'Health Care'},
  {sym: 'ZION', name: 'Zions Bancorp', industry: 'Financials'},
  {sym: 'ZTS', name: 'Zoetis', industry: 'Health Care'}
];

module.exports = tickers;
